package com.exercise.exercise.mapper;

import com.exercise.exercise.dataobject.ActivityDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface ActivityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    int insert(ActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    int insertSelective(ActivityDO record);



    @Select("select * from activity")
    @Results({
            @Result(column = "user_id",property = "userId"),
            @Result(column = "activity_id",property = "activityId")
    })
    List<ActivityDO> getActivities();

    @Select("select peopleNum from activity where activity_id = #{activityId}")
    int getPeopleNum(@Param("activityId")String activityId);

}