package com.exercise.exercise.mapper;

import com.exercise.exercise.dataobject.MessageDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface MessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    int insert(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    int insertSelective(MessageDO record);

    @Select("select * from message where activity_id = #{activityId}")
    @Results({
            @Result(column = "user_id",property = "userId"),
            @Result(column = "activity_id",property = "activityId"),
            @Result(column = "message_id",property = "messageId")
    })
    List<MessageDO> selectByActivityId(@Param("activityId")String activityId);
}