package com.exercise.exercise.mapper;

import com.exercise.exercise.dataobject.UserActivityDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface UserActivityDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Sat May 05 04:38:08 CST 2018
     */
    int insert(UserActivityDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbg.generated Sat May 05 04:38:08 CST 2018
     */
    int insertSelective(UserActivityDO record);

    @Select("select * from user_activity where activity_id = #{activityId}")
    @Results({
            @Result(column = "user_id",property = "userId"),
            @Result(column = "activity_id",property = "activityId")
    })
    List<UserActivityDO> getJoinPeople(@Param("activityId")String activityId);

    @Select("select count(*) from user_activity where activity_id = #{activityId}")
    int getJoinNum(@Param("activityId")String activityId);

    @Select("select * from user_activity where activity_id = #{activityId} and user_id = #{userId}")
    @Results({
            @Result(column = "user_id",property = "userId"),
            @Result(column = "activity_id",property = "activityId")
    })
    UserActivityDO getUserInfoByActivity(@Param("userId")String userId,@Param("activityId")String activityId);
}