package com.exercise.exercise.mapper;

import com.exercise.exercise.dataobject.UserInfoDO;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;

public interface UserInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat May 05 03:14:39 CST 2018
     */
    int insert(UserInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat May 05 03:14:39 CST 2018
     */
    int insertSelective(UserInfoDO record);


    @Select("select * from user_info where username = #{username}")
    @Results({
            @Result(column = "user_id",property = "userId")
    })
    UserInfoDO selectByUsername(@Param("username")String username);
}