package com.exercise.exercise.dataobject;

import java.util.Date;

public class ActivityDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.name
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.date
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.place
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.peopleNum
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    private Integer peoplenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.user_id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    private String activityId;

    public ActivityDO(String name, Date date, String place, Integer peoplenum, String userId, String activityId) {
        this.name = name;
        this.date = date;
        this.place = place;
        this.peoplenum = peoplenum;
        this.userId = userId;
        this.activityId = activityId;
    }

    public ActivityDO() {
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.name
     *
     * @return the value of activity.name
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.name
     *
     * @param name the value for activity.name
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.date
     *
     * @return the value of activity.date
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.date
     *
     * @param date the value for activity.date
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.place
     *
     * @return the value of activity.place
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.place
     *
     * @param place the value for activity.place
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.peopleNum
     *
     * @return the value of activity.peopleNum
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public Integer getPeoplenum() {
        return peoplenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.peopleNum
     *
     * @param peoplenum the value for activity.peopleNum
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public void setPeoplenum(Integer peoplenum) {
        this.peoplenum = peoplenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.user_id
     *
     * @return the value of activity.user_id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.user_id
     *
     * @param userId the value for activity.user_id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_id
     *
     * @return the value of activity.activity_id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_id
     *
     * @param activityId the value for activity.activity_id
     *
     * @mbg.generated Sun Apr 29 19:53:04 CST 2018
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId == null ? null : activityId.trim();
    }
}